#include "GPIO.h"
#include "sysctrl.h"

void portFInit(void)
{
	SYSCTLCGCGPIO |=0X20;
	while((SYSCTL_PRGPIO & 0X20)==0);
	GPIO_PORTF_LOCK =0X4C4F434B;
	GPIO_PORTF_CR |= 0X4;
	GPIO_PORTF_AMSEL &= ~0X1F;
	GPIO_PORTF_AFSEL &= ~0X1F;
	GPIO_PORTF_PCTL &= ~0X000FFFFF;
	GPIO_PORTF_DIR |= 0X04;
	GPIO_PORTF_DEN |= 0X04;
	GPIO_PORTF_DATA|= 0X04;
}